#############################################################################
# Makefile for building: mvd
# Generated by qmake (2.01a) (Qt 4.6.2) on: Tue Mar 27 13:41:55 2012
# Project:  images.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile images.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_PHONON_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fomit-frame-pointer -march=i586 -mtune=generic -fasynchronous-unwind-tables -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fomit-frame-pointer -march=i586 -mtune=generic -fasynchronous-unwind-tables -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib/qt4/mkspecs/linux-g++ -I. -I/usr/lib/qt4/include/QtCore -I/usr/lib/qt4/include/QtGui -I/usr/lib/qt4/include/phonon -I/usr/lib/qt4/include -I/usr/lib/qt4/include/phonon_compat -I. -I.
LINK          = g++
LFLAGS        = -Wl,--as-needed -Wl,--no-undefined -Wl,-z,relro -Wl,-O1 -Wl,--build-id -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib -lphonon -lQtGui -L/usr/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		sequencemodel.cpp \
		node.cpp \
		delegate.cpp \
		nodepropertiesdialog.cpp \
		effect.cpp \
		slideshowengine.cpp \
		moviepropertiesdialog.cpp \
		soundtracksdialog.cpp \
		soundengine.cpp moc_mainwindow.cpp \
		moc_sequencemodel.cpp \
		moc_pixmap.cpp \
		moc_delegate.cpp \
		moc_nodepropertiesdialog.cpp \
		moc_slideshowengine.cpp \
		moc_moviepropertiesdialog.cpp \
		moc_soundtracksdialog.cpp \
		qrc_images.cpp
OBJECTS       = main.o \
		mainwindow.o \
		sequencemodel.o \
		node.o \
		delegate.o \
		nodepropertiesdialog.o \
		effect.o \
		slideshowengine.o \
		moviepropertiesdialog.o \
		soundtracksdialog.o \
		soundengine.o \
		moc_mainwindow.o \
		moc_sequencemodel.o \
		moc_pixmap.o \
		moc_delegate.o \
		moc_nodepropertiesdialog.o \
		moc_slideshowengine.o \
		moc_moviepropertiesdialog.o \
		moc_soundtracksdialog.o \
		qrc_images.o
DIST          = /usr/lib/qt4/mkspecs/common/g++.conf \
		/usr/lib/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/lib/qt4/mkspecs/qconfig.pri \
		/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/lib/qt4/mkspecs/features/release.prf \
		/usr/lib/qt4/mkspecs/features/default_post.prf \
		/usr/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/lib/qt4/mkspecs/features/qt.prf \
		/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib/qt4/mkspecs/features/moc.prf \
		/usr/lib/qt4/mkspecs/features/resources.prf \
		/usr/lib/qt4/mkspecs/features/uic.prf \
		/usr/lib/qt4/mkspecs/features/yacc.prf \
		/usr/lib/qt4/mkspecs/features/lex.prf \
		/usr/lib/qt4/mkspecs/features/include_source_dir.prf \
		images.pro
QMAKE_TARGET  = mvd
DESTDIR       = 
TARGET        = mvd

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_nodepropertiesdialog.h ui_moviepropertiesdialog.h ui_soundtracksdialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: images.pro  /usr/lib/qt4/mkspecs/linux-g++/qmake.conf /usr/lib/qt4/mkspecs/common/g++.conf \
		/usr/lib/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/lib/qt4/mkspecs/qconfig.pri \
		/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/lib/qt4/mkspecs/features/release.prf \
		/usr/lib/qt4/mkspecs/features/default_post.prf \
		/usr/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/lib/qt4/mkspecs/features/qt.prf \
		/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib/qt4/mkspecs/features/moc.prf \
		/usr/lib/qt4/mkspecs/features/resources.prf \
		/usr/lib/qt4/mkspecs/features/uic.prf \
		/usr/lib/qt4/mkspecs/features/yacc.prf \
		/usr/lib/qt4/mkspecs/features/lex.prf \
		/usr/lib/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile images.pro
/usr/lib/qt4/mkspecs/common/g++.conf:
/usr/lib/qt4/mkspecs/common/unix.conf:
/usr/lib/qt4/mkspecs/common/linux.conf:
/usr/lib/qt4/mkspecs/qconfig.pri:
/usr/lib/qt4/mkspecs/features/qt_functions.prf:
/usr/lib/qt4/mkspecs/features/qt_config.prf:
/usr/lib/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt4/mkspecs/features/default_pre.prf:
/usr/lib/qt4/mkspecs/features/release.prf:
/usr/lib/qt4/mkspecs/features/default_post.prf:
/usr/lib/qt4/mkspecs/features/warn_on.prf:
/usr/lib/qt4/mkspecs/features/qt.prf:
/usr/lib/qt4/mkspecs/features/unix/thread.prf:
/usr/lib/qt4/mkspecs/features/moc.prf:
/usr/lib/qt4/mkspecs/features/resources.prf:
/usr/lib/qt4/mkspecs/features/uic.prf:
/usr/lib/qt4/mkspecs/features/yacc.prf:
/usr/lib/qt4/mkspecs/features/lex.prf:
/usr/lib/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile images.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/mvd1.0.0 || $(MKDIR) .tmp/mvd1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/mvd1.0.0/ && $(COPY_FILE) --parents mainwindow.h sequencemodel.h node.h pixmap.h delegate.h nodepropertiesdialog.h effect.h slideshowengine.h moviepropertiesdialog.h const.h soundtracksdialog.h .tmp/mvd1.0.0/ && $(COPY_FILE) --parents images.qrc images.qrc .tmp/mvd1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp sequencemodel.cpp node.cpp delegate.cpp nodepropertiesdialog.cpp effect.cpp slideshowengine.cpp moviepropertiesdialog.cpp soundtracksdialog.cpp soundengine.cpp .tmp/mvd1.0.0/ && $(COPY_FILE) --parents mainwindow.ui nodepropertiesdialog.ui moviepropertiesdialog.ui soundtracksdialog.ui .tmp/mvd1.0.0/ && (cd `dirname .tmp/mvd1.0.0` && $(TAR) mvd1.0.0.tar mvd1.0.0 && $(COMPRESS) mvd1.0.0.tar) && $(MOVE) `dirname .tmp/mvd1.0.0`/mvd1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/mvd1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_sequencemodel.cpp moc_pixmap.cpp moc_delegate.cpp moc_nodepropertiesdialog.cpp moc_slideshowengine.cpp moc_moviepropertiesdialog.cpp moc_soundtracksdialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_sequencemodel.cpp moc_pixmap.cpp moc_delegate.cpp moc_nodepropertiesdialog.cpp moc_slideshowengine.cpp moc_moviepropertiesdialog.cpp moc_soundtracksdialog.cpp
moc_mainwindow.cpp: sequencemodel.h \
		node.h \
		effect.h \
		pixmap.h \
		delegate.h \
		slideshowengine.h \
		mainwindow.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_sequencemodel.cpp: node.h \
		effect.h \
		pixmap.h \
		sequencemodel.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) sequencemodel.h -o moc_sequencemodel.cpp

moc_pixmap.cpp: pixmap.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) pixmap.h -o moc_pixmap.cpp

moc_delegate.cpp: delegate.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) delegate.h -o moc_delegate.cpp

moc_nodepropertiesdialog.cpp: sequencemodel.h \
		node.h \
		effect.h \
		pixmap.h \
		nodepropertiesdialog.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) nodepropertiesdialog.h -o moc_nodepropertiesdialog.cpp

moc_slideshowengine.cpp: node.h \
		effect.h \
		pixmap.h \
		sequencemodel.h \
		slideshowengine.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) slideshowengine.h -o moc_slideshowengine.cpp

moc_moviepropertiesdialog.cpp: sequencemodel.h \
		node.h \
		effect.h \
		pixmap.h \
		moviepropertiesdialog.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) moviepropertiesdialog.h -o moc_moviepropertiesdialog.cpp

moc_soundtracksdialog.cpp: sequencemodel.h \
		node.h \
		effect.h \
		pixmap.h \
		soundtracksdialog.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) soundtracksdialog.h -o moc_soundtracksdialog.cpp

compiler_rcc_make_all: qrc_images.cpp qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp qrc_images.cpp
qrc_images.cpp: images.qrc \
		resources/square_red.png \
		resources/qled.png \
		resources/film.svg \
		resources/open.svg \
		resources/open.png \
		resources/icon2.png \
		resources/open2.svg \
		resources/stop-red.svg \
		resources/paint.svg \
		resources/photoframe.svg \
		resources/notes.svg \
		resources/icon3.png \
		resources/open3.svg \
		resources/save.png \
		resources/start.png \
		resources/led_triangular_1_green.png \
		resources/cd2.svg \
		resources/refresh.svg \
		resources/pause.svg \
		resources/stop.png \
		resources/mixer.svg \
		resources/new.svg \
		resources/monitor.svg \
		resources/note2.svg \
		resources/left.png \
		resources/tools.svg \
		resources/go-down.svg \
		resources/clock.svg \
		resources/minus.svg \
		resources/arrows.svg \
		resources/slides.svg \
		resources/plus.svg \
		resources/save.svg \
		resources/movie.svg \
		resources/dossier.svg \
		resources/note.svg \
		resources/go.svg \
		resources/stop.svg \
		resources/new.png \
		resources/colors.svg \
		resources/icon.png \
		resources/go-up.svg \
		resources/dvd.svg
	/usr/lib/qt4/bin/rcc -name images images.qrc -o qrc_images.cpp

qrc_images.cpp: images.qrc \
		resources/square_red.png \
		resources/qled.png \
		resources/film.svg \
		resources/open.svg \
		resources/open.png \
		resources/icon2.png \
		resources/open2.svg \
		resources/stop-red.svg \
		resources/paint.svg \
		resources/photoframe.svg \
		resources/notes.svg \
		resources/icon3.png \
		resources/open3.svg \
		resources/save.png \
		resources/start.png \
		resources/led_triangular_1_green.png \
		resources/cd2.svg \
		resources/refresh.svg \
		resources/pause.svg \
		resources/stop.png \
		resources/mixer.svg \
		resources/new.svg \
		resources/monitor.svg \
		resources/note2.svg \
		resources/left.png \
		resources/tools.svg \
		resources/go-down.svg \
		resources/clock.svg \
		resources/minus.svg \
		resources/arrows.svg \
		resources/slides.svg \
		resources/plus.svg \
		resources/save.svg \
		resources/movie.svg \
		resources/dossier.svg \
		resources/note.svg \
		resources/go.svg \
		resources/stop.svg \
		resources/new.png \
		resources/colors.svg \
		resources/icon.png \
		resources/go-up.svg \
		resources/dvd.svg
	/usr/lib/qt4/bin/rcc -name images images.qrc -o qrc_images.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_nodepropertiesdialog.h ui_moviepropertiesdialog.h ui_soundtracksdialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_nodepropertiesdialog.h ui_moviepropertiesdialog.h ui_soundtracksdialog.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib/qt4/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_nodepropertiesdialog.h: nodepropertiesdialog.ui
	/usr/lib/qt4/bin/uic nodepropertiesdialog.ui -o ui_nodepropertiesdialog.h

ui_moviepropertiesdialog.h: moviepropertiesdialog.ui
	/usr/lib/qt4/bin/uic moviepropertiesdialog.ui -o ui_moviepropertiesdialog.h

ui_soundtracksdialog.h: soundtracksdialog.ui
	/usr/lib/qt4/bin/uic soundtracksdialog.ui -o ui_soundtracksdialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		sequencemodel.h \
		node.h \
		effect.h \
		pixmap.h \
		delegate.h \
		slideshowengine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp const.h \
		effect.h \
		node.h \
		pixmap.h \
		delegate.h \
		mainwindow.h \
		sequencemodel.h \
		slideshowengine.h \
		ui_mainwindow.h \
		nodepropertiesdialog.h \
		moviepropertiesdialog.h \
		soundtracksdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

sequencemodel.o: sequencemodel.cpp node.h \
		effect.h \
		pixmap.h \
		sequencemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sequencemodel.o sequencemodel.cpp

node.o: node.cpp const.h \
		node.h \
		effect.h \
		pixmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o node.o node.cpp

delegate.o: delegate.cpp node.h \
		effect.h \
		pixmap.h \
		delegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o delegate.o delegate.cpp

nodepropertiesdialog.o: nodepropertiesdialog.cpp nodepropertiesdialog.h \
		sequencemodel.h \
		node.h \
		effect.h \
		pixmap.h \
		ui_nodepropertiesdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o nodepropertiesdialog.o nodepropertiesdialog.cpp

effect.o: effect.cpp effect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o effect.o effect.cpp

slideshowengine.o: slideshowengine.cpp mainwindow.h \
		sequencemodel.h \
		node.h \
		effect.h \
		pixmap.h \
		delegate.h \
		slideshowengine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o slideshowengine.o slideshowengine.cpp

moviepropertiesdialog.o: moviepropertiesdialog.cpp moviepropertiesdialog.h \
		sequencemodel.h \
		node.h \
		effect.h \
		pixmap.h \
		ui_moviepropertiesdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moviepropertiesdialog.o moviepropertiesdialog.cpp

soundtracksdialog.o: soundtracksdialog.cpp soundtracksdialog.h \
		sequencemodel.h \
		node.h \
		effect.h \
		pixmap.h \
		ui_soundtracksdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o soundtracksdialog.o soundtracksdialog.cpp

soundengine.o: soundengine.cpp slideshowengine.h \
		node.h \
		effect.h \
		pixmap.h \
		sequencemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o soundengine.o soundengine.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_sequencemodel.o: moc_sequencemodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sequencemodel.o moc_sequencemodel.cpp

moc_pixmap.o: moc_pixmap.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pixmap.o moc_pixmap.cpp

moc_delegate.o: moc_delegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_delegate.o moc_delegate.cpp

moc_nodepropertiesdialog.o: moc_nodepropertiesdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_nodepropertiesdialog.o moc_nodepropertiesdialog.cpp

moc_slideshowengine.o: moc_slideshowengine.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_slideshowengine.o moc_slideshowengine.cpp

moc_moviepropertiesdialog.o: moc_moviepropertiesdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_moviepropertiesdialog.o moc_moviepropertiesdialog.cpp

moc_soundtracksdialog.o: moc_soundtracksdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_soundtracksdialog.o moc_soundtracksdialog.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

